spring:
  application:
    name: marpc-demo-consumer

server:
  port: 7085

marpc:
  # 注册中心配置 - 可选: zookeeper | maregistry
  registry:
    #    type: zookeeper  # 默认使用 zookeeper
    #  zk:
    #    address: localhost:2181
    type: maregistry
  maregistry:
    address: http://localhost:8484
  app: marpc-app
  env: dev
  provider:
    instance: localhost:8080
  loadbalancer: roundrobin
  filter:
    cache:
      enabled: true
    mock:
      enabled: true
  retry:
    maxRetries: 2
    timeout: 3000
    switchInstanceOnRetry: true
  circuitbreaker:
    enabled: false
    faultLimit: 5
    halfOpenInitialDelay: 10000
    halfOpenDelay: 5000
    windowSize: 10
  router:
    gray:
      enabled: false
      ratio: 50
  transport: netty
  netty:
    port: 9091
