spring:
  application:
    name: marpc-demo-consumer

server:
  port: 9081

marpc:
  zk:
    address: localhost:2181
  app: marpc-app
  env: dev
  provider:
    instance: localhost:8080
  loadbalancer: roundrobin
  filter:
    cache:
      enabled: true
    mock:
      enabled: true
