spring:
  application:
    name: marpc-demo-provider

server:
  port: 7081

marpc:
  # 注册中心配置 - 可选: zookeeper | maregistry
  registry:
#    type: zookeeper  # 默认使用 zookeeper
#  zk:
#    address: localhost:2181
    type: maregistry
  maregistry:
    address: http://localhost:8484
  app: marpc-app
  env: dev
#  provider:
#    instance: localhost:8080
  loadbalancer: roundrobin
  transport: netty
  netty:
    port: 9091
    server:
      enabled: true
